swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all future endpoints of the project
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/{accountId}/getTransactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Get User Transactions
      description: Retrieve all transactions for the authenticated user
      parameters:
        - in: path
          name: accountId
          description: ID of the account for which transactions are requested
          required: true
          type: string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Successful response containing user transactions
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '400':
          description: Bad request. Invalid parameters provided.
        '500':
          description: Internal Server Error
  /transaction/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Get Transaction Details
      description: Retrieve details of a transaction by its ID using a token
      parameters:
        - in: path
          name: transactionId
          description: ID of the transaction for which details are requested
          required: true
          type: integer
          format: int64
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Successful response containing transaction details
          schema:
            type: object
            $ref: '#/definitions/TransactionDetails'
        '400':
          description: Bad request. Invalid transaction token provided.
        '404':
          description: Transaction not found.
        '500':
          description: Internal Server Error
  /transaction/{transactionId}/update:
    put:
      security:
        - Bearer: []
      tags:
        - Transactions
      summary: Update Transaction
      description: Update the content of a transaction using its token
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Update transaction details
          required: true
          schema:
            $ref: '#/definitions/TransactionDetails'

      produces:
        - application/json
      responses:
        '200':
          description: Successful response indicating that the transaction has been updated
          schema:
            type: object  # Define the structure of the response if needed
        '400':
          description: Bad request. Invalid transaction token or content provided.
        '404':
          description: Transaction not found.
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    type: object
    properties:
      id:
        type: integer
        format: int64
      amount: 
        type: number
        format: float
      balance: 
        type: number
        format: float
      description:
        type: string
      date:
        type: string
        format: date-time
  TransactionDetails: 
    type: object
    properties:            
      category:
        type: string
      notes:
        type: string